module.exports = {
  setting: {
    MaxLocalstorageSize: 10,
    MaxWebviewDepth: 5,
    ExpendedMaxWebviewDepth: 5,
    MaxBackgroundLifespan: 300,
    MaxRequestConcurrent: 5,
    MaxUploadConcurrent: 1,
    MaxDownloadConcurrent: 10,
    MaxFileStorageSize: 100,
    MinTabbarCount: 2,
    MaxTabbarCount: 5,
    MaxTabbarIconSize: 40,
    MaxDataSize: 1048576,
    MaxWebsocketConnect: 5,
    GameDownloadFileSizeLimit: 50,
    DownloadFileSizeLimit: 10,
    NavigateMiniprogramLimit: 10,
    GroupIdListLimit: 10,
    MaxSubPackageLimit: 100,
    MaxCodeSize: 2,
    MaxSubpackageSubCodeSize: 2,
    MaxSubpackageFullCodeSize: 24,
    MaxGameMainPkgCodeSize: 4,
    MaxGameSubpackageSubCodeSize: 6,
    MaxGameSubpackageFullCodeSize: 10
  },
  MAX_PAGE_STACK_DEPTH: 5,
  DEFAULT_NAVIGATIONBAR_WHITE_TEXTCOLOR: "#f8f8f8",
  DEFAULT_NAVIGATIONBAR_BLACK_TEXTCOLOR: "#000000",
  DEFAULT_NAVIGATIONBAR_BGCOLOR: "#000000",
  default_tabBarBorderBlackColor: "rgba(0, 0, 0, 0.33)",
  default_tabBarBorderWhiteColor: "rgba(255, 255, 255, 0.33)",
  default_backgroundColor: "#ffffff",
  default_android_tabbar_height: 54,
  default_ios_tabbar_height: 48,
  default_android_navigationbar_height: 48,
  default_ios_navigationbar_height: 44,
  default_statusbar_height: 20,
  default_search_widget_radio: 0.6,
  default_conversation_widget_radio: 0.8,
  NO_BOM_VAR: [
    "window",
    "document",
    "frames",
    "self",
    "location",
    "navigator",
    "localStorage",
    "history",
    "Caches",
    "screen",
    "alert",
    "confirm",
    "prompt",
    "fetch",
    "XMLHttpRequest",
    "WebSocket",
    "webkit",
    "WeixinJSCore",
    "Reporter",
    "print",
    "URL",
    "DOMParser",
    "upload",
    "preview",
    "build",
    "showDecryptedInfo",
    "syncMessage",
    "checkProxy",
    "showSystemInfo",
    "openVendor",
    "openToolsLog",
    "showRequestInfo",
    "help",
    "showDebugInfoTable",
    "closeDebug",
    "showDebugInfo",
    "__global"
  ],
  whiteFileExtName: {
    ".wxml": true,
    ".wxss": true,
    ".wxs": true,
    ".png": true,
    ".jpg": true,
    ".jpeg": true,
    ".gif": true,
    ".svg": true,
    ".js": true,
    ".json": true,
    ".cer": true,
    ".mp3": true,
    ".aac": true,
    ".m4a": true,
    ".mp4": true,
    ".wav": true,
    ".ogg": true,
    ".silk": true
  },
  gameWhiteFileExtName: {
    ".png": true,
    ".jpg": true,
    ".jpeg": true,
    ".gif": true,
    ".svg": true,
    ".js": true,
    ".json": true,
    ".cer": true,
    ".obj": true,
    ".dae": true,
    ".fbx": true,
    ".mtl": true,
    ".stl": true,
    ".3ds": true,
    ".mp3": true,
    ".pvr": true,
    ".wav": true,
    ".plist": true,
    ".ttf": true,
    ".fnt": true,
    ".gz": true,
    ".ccz": true,
    ".m4a": true,
    ".mp4": true,
    ".bmp": true,
    ".atlas": true,
    ".swf": true,
    ".ani": true,
    ".part": true,
    ".proto": true,
    ".bin": true,
    ".sk": true,
    ".mipmaps": true,
    ".txt": true,
    ".zip": true,
    ".ogg": true,
    ".silk": true,
    ".dbbin": true,
    ".dbmv": true,
    ".etc": true,
    ".lmat": true,
    ".lm": true,
    ".ls": true,
    ".lh": true,
    ".lani": true,
    ".lav": true,
    ".lsani": true,
    ".ltc": true,
    ".csv": true,
    ".scene": true,
    ".prefab": true,
    ".lml": true,
    ".lmani": true,
    ".ktx": true,
    ".dds": true,
    ".xml": true
  },
  errorPrefix: {
    COMPONENT_FOR_DEVELOPER: "For developer:",
    WXML_RUNTIME_ERROR: "WXMLRT",
    WXML_RUNTIME_ERROR_REG: /^WXMLRT_[^:]*:/,
    WXML_PLUGIN_RUNTIME_ERROR_REG: /^WXMLRT_\$plugin_([^_]*)_([^:]*):/,
    WXS_RUNTIME_ERROR: "WXSRT",
    WEBVIEW_ERROR: "WEBVIEW_ERROR",
    CODE_ERROR: "CODE_ERROR"
  },
  weappUsrFilePathPrefix: "usr",
  weappTmpFilePathPrefix: "tmp",
  weappStoreFilePathPrefix: "store",
  SCENE_DEFAULT: 1001,
  SCENE_SHARE_TICKET: 1044,
  SCENE_MINI_PROGRAM: 1037,
  SCENE_MINI_PROGRAM_BACK: 1038,
  SCENE_GROUP_SHARE: 1008,
  SCENE_SINGLE_SHARE: 1007,
  SCENE_PROFILE: 1020,
  SCENE_CUSTOM_MENU: 1035,
  SCENE_APP_SHARE_MESSAGE: 1036,
  SCENE_TEMPLETE_MESSAGE: 1043,
  MINI_PROGRAM_MAIN_PACKAGE_ROOT: "__APP__",
  APP_TYPE: {
    NORMAL: 0,
    PLUGIN: 1,
    SHOP: 2,
    MINISHOP: 3,
    GAME: 4,
    CARD: 5,
    NATIVE: 7
  }
};
