//global.appConfig.isDev || g.push('WeixinJSBridge');
module.exports = {
  MAX_PAGE_STACK_DEPTH: 5,
  DEFAULT_NAVIGATIONBAR_WHITE_TEXTCOLOR: '#f8f8f8',
  DEFAULT_NAVIGATIONBAR_BLACK_TEXTCOLOR: '#000000',
  DEFAULT_NAVIGATIONBAR_BGCOLOR: '#000000',
  default_tabBarBorderBlackColor: 'rgba(0, 0, 0, 0.33)',
  default_tabBarBorderWhiteColor: 'rgba(255, 255, 255, 0.33)',
  default_backgroundColor: '#ffffff',
  default_android_tabbar_height: 54,
  default_ios_tabbar_height: 48,
  default_android_navigationbar_height: 48,
  default_ios_navigationbar_height: 44,
  default_statusbar_height: 20,
  default_search_widget_radio: 0.6,
  default_conversation_widget_radio: 0.8,
  NO_BOM_VAR: ['window', 'document', 'frames', 'self', 'location', 'navigator', 'localStorage', 'history', 'Caches', 'screen', 'alert', 'confirm', 'prompt', 'fetch', 'XMLHttpRequest', 'WebSocket', 'webkit', 'WeixinJSCore', 'Reporter', 'print', 'URL', 'DOMParser', 'upload', 'preview', 'build', 'showDecryptedInfo', 'syncMessage', 'checkProxy', 'showSystemInfo', 'openVendor', 'openToolsLog', 'showRequestInfo', 'help', 'showDebugInfoTable', 'closeDebug', 'showDebugInfo', '__global'],
  setting: {
    MaxLocalstorageSize: 10,
    MaxCodeSize: 5,
    MaxWebviewDepth: 5,
    ExpendedMaxWebviewDepth: 5,
    MaxBackgroundLifespan: 300,
    MaxRequestConcurrent: 5,
    MaxUploadConcurrent: 1,
    MaxDownloadConcurrent: 10,
    MaxFileStorageSize: 100,
    MinTabbarCount: 2,
    MaxTabbarCount: 5,
    MaxTabbarIconSize: 40,
    MaxDataSize: 1048576,
    MaxWebsocketConnect: 2,
    GameDownloadFileSizeLimit: 50,
    DownloadFileSizeLimit: 10,
    NavigateMiniprogramLimit: 10,
    GroupIdListLimit:10,
    MaxSubPackageLimit: 100
  },
  MINI_PROGRAM_MAIN_PACKAGE_ROOT: '__APP__',
  whiteFileExtName: {
    ".wxml": true,
    '.qml': true,
    ".wxss": true,
    '.qss': true,
    ".wxs": true,
    '.qs': true,
    ".png": true,
    ".jpg": true,
    ".jpeg": true,
    ".gif": true,
    ".svg": true,
    ".js": true,
    ".json": true,
    ".cer": true,
    ".mp3": true,
    ".aac": true,
    ".m4a": true,
    ".mp4": true,
    ".wav": true,
    ".ogg": true,
    ".silk": true
  },
  gameWhiteFileExtName: {
    ".png": true,
    ".jpg": true,
    ".jpeg": true,
    ".gif": true,
    ".svg": true,
    ".js": true,
    ".json": true,
    ".cer": true,
    ".obj": true,
    ".dae": true,
    ".fbx": true,
    ".mtl": true,
    ".stl": true,
    ".3ds": true,
    ".mp3": true,
    ".pvr": true,
    ".wav": true,
    ".plist": true,
    ".ttf": true,
    ".fnt": true,
    ".gz": true,
    ".ccz": true,
    ".m4a": true,
    ".mp4": true,
    ".bmp": true,
    ".atlas": true,
    ".swf": true,
    ".ani": true,
    ".part": true,
    ".proto": true,
    ".bin": true,
    ".sk": true,
    ".mipmaps": true,
    ".txt": true,
    ".zip": true,
    ".ogg": true,
    ".silk": true,
    ".dbbin": true,
    ".dbmv": true,
    ".etc": true,
    ".lmat": true,
    ".lm": true,
    ".ls": true,
    ".lh": true,
    ".lani": true,
    ".lav": true,
    ".lsani": true,
    ".ltc": true,
    ".csv": true,
    ".scene": true,
    ".prefab": true,
    ".lml": true,
    ".lmani": true,
    ".ktx": true,
    ".dds": true,
    ".xml": true
  },
  mimesMap: {
    png: 'image/png',
    jpeg: 'image/jpeg',
    jpg: 'image/jpeg',
    gif: 'image/gif',
    bmp: 'image/bmp',
    js: 'text/javascript; charset=UTF-8',
    html: 'text/html; charset=UTF-8',
    svg: 'image/svg+xml'
  },
  APP_TYPE: {
    NORMAL: 0,
    PLUGIN: 1,
    SHOP: 2,
    MINISHOP: 3,
    GAME: 4,
    CARD: 5,
    NATIVE: 7
  }
}
