const whiteFileExtName = {
  ".wxml": true,
  ".wxss": true,
  ".qml": true,
  ".qss": true,
  ".wxs": true,
  ".qs": true,
  ".png": true,
  ".jpg": true,
  ".jpeg": true,
  ".gif": true,
  ".svg": true,
  ".js": true,
  ".json": true,
  ".cer": true,
  ".mp3": true,
  ".aac": true,
  ".m4a": true,
  ".mp4": true,
  ".wav": true,
  ".ogg": true,
  ".silk": true
};
const gameWhiteFileExtName = {
  ".png": true,
  ".jpg": true,
  ".jpeg": true,
  ".gif": true,
  ".svg": true,
  ".js": true,
  ".json": true,
  ".cer": true,
  ".obj": true,
  ".dae": true,
  ".fbx": true,
  ".mtl": true,
  ".stl": true,
  ".3ds": true,
  ".mp3": true,
  ".pvr": true,
  ".wav": true,
  ".plist": true,
  ".ttf": true,
  ".fnt": true,
  ".gz": true,
  ".ccz": true,
  ".m4a": true,
  ".mp4": true,
  ".bmp": true,
  ".atlas": true,
  ".swf": true,
  ".ani": true,
  ".part": true,
  ".proto": true,
  ".bin": true,
  ".sk": true,
  ".mipmaps": true,
  ".txt": true,
  ".zip": true,
  ".ogg": true,
  ".silk": true,
  ".dbbin": true,
  ".dbmv": true,
  ".etc": true,
  ".lmat": true,
  ".lm": true,
  ".ls": true,
  ".lh": true,
  ".lani": true,
  ".lav": true,
  ".lsani": true,
  ".ltc": true,
  ".csv": true,
  ".scene": true,
  ".prefab": true,
  ".lml": true,
  ".lmani": true,
  ".ktx": true,
  ".dds": true,
  ".xml": true
};

const mimesMap = {
  png: "image/png",
  jpeg: "image/jpeg",
  jpg: "image/jpeg",
  gif: "image/gif",
  bmp: "image/bmp",
  js: "text/javascript; charset=UTF-8",
  html: "text/html; charset=UTF-8",
  svg: "image/svg+xml"
};

module.exports = {
  whiteFileExtName,
  gameWhiteFileExtName,
  mimesMap
};
